DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Doe",
    "number": "567-7397523"
}

###
GET  http://localhost:3001/api/persons