DELETE http://localhost:3001/api/persons/655b49d64ef39f918fa3a557

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "John Smith",
    "number": "567-7397523"
}

###
GET  http://localhost:3001/api/persons

###
GET https://fullstack-phonebook-app-nz40.onrender.com/api/persons

###
GET http://localhost:3001/api/persons/655b52c588f38743468ea2db